ecommerce/ecommerce_backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls'), name='main'),
    path('auth/', include('authenticate.urls'), name='authenticate'),
    path('product/', include('products.urls'), name='products'),
    path('user/', include('users.urls'), name='users'),
    path('order/', include('orders.urls'), name='orders'),
    path('', include('reports.urls'), name='reports')
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/main/urls.py
from django.urls import path
from django.views.generic import TemplateView
from rest_framework.schemas import get_schema_view
from main.views import *

app_name = "main"

urlpatterns = [
    path('openapi/', get_schema_view(
            title="Your Project",
            description="API for all things …",
            version="1.0.0"
        ), name='openapi-schema'),
    path('swagger/', TemplateView.as_view(
        template_name='swagger.html',
        extra_context={'schema_url':'main:openapi-schema'}
    ), name='swagger-ui'),
    path('banners/', ListBannersView.as_view(), name='list-banners'),
    path('coupon/list/', ListActiveCouponsView.as_view(), name='list-coupons'),
    path('coupon/check/', CheckCouponView.as_view(), name='check-coupun'),
    path('version/', GetAppVersionView.as_view(), name='app-version'),

    # App home page data
    path('home/', AppHomeView.as_view(), name='home-data'),
]

ecommerce/reports/urls.py
from django.urls import path
from reports.views import *

app_name = 'reports'

urlpatterns = [
    path('login/', login_process, name='login'),
    path('logout/', logout_process, name='logout'),
    path('', dashboard, name='dashboard'),

    # customers
    path('customers/statistics/', customers_statistics, name='customer-statistics'),

    # products
    path('products/statistics/', products_statistics, name='product-statistics'),
    path('products/stock/', products_running_out, name='products-running-out'),

    # orders
    path('orders/statistics/', orders_statistics, name='order-statistics'),
    path('orders/all/', all_orders, name='all-orders'),
    path('orders/<int:order_no>/', one_order, name='one-order'),
    path('orders/pdf/<int:id>/', order_pdf, name='order-pdf'),

    # reports
    path('reports/sheets/', sheets, name='sheets'),
    path('reports/export/<str:type>/', export_sheet, name='export-sheets'),

    # errors
    path('error/', unauthorized, name='unauthorized')
]

ecommerce/orders/models/order.py
from django.db import models
from users.models import User, Address
from main.models import Coupon, ShippingFee, Currency
from utils import OrderStatusChoices, CouponTypesChoices, OrderPaymentOptionChoices
from utils import send_email

class Order(models.Model):
    order_no = models.IntegerField(unique=True, blank=True, null=True)
    customer = models.ForeignKey(User, on_delete=models.CASCADE, related_name='customer_order')
    currency = models.ForeignKey(Currency, on_delete=models.SET_NULL, null=True)
    coupon = models.ForeignKey(Coupon, blank=True, null=True, on_delete=models.CASCADE)
    address = models.ForeignKey(Address, on_delete=models.SET_NULL, blank=True, null=True)
    phone = models.CharField(max_length=20)
    notes = models.TextField(blank=True,null=True)
    payment_option = models.PositiveIntegerField(choices=OrderPaymentOptionChoices.choices, default= OrderPaymentOptionChoices.ON_DELIVERY)
    shipping_fees = models.ForeignKey(ShippingFee, on_delete=models.SET_NULL, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    status = models.PositiveIntegerField(choices=OrderStatusChoices.choices, default=OrderStatusChoices.PENDING)
    last_action_date = models.DateTimeField(auto_now=True)

    @property
    def total_cost(self):
        total = sum(item.get_cost() for item in self.ordered_items.all())

        # Coupons
        if self.coupon:
            if self.coupon.discount_type == CouponTypesChoices.PERCENTAGE:
                total = total - ((total * self.coupon.discount) / 100)
            else:
                total -= self.coupon.discount

        # Shipping Fees
        if self.shipping_fees:
            total += self.shipping_fees.amount
            
        return total

    def order_submit_email(self):
        send_email(
                subject="Order Details",
                template_name="order_info.html",
                context={
                    "name" : self.customer.first_name,
                    "order" : self,
                    "items" : self.ordered_items.all(),
                    "total" : self.total_cost
                },
                to=[self.customer.email]
            )
        return

ecommerce/users/models/user.py
from django.db import models
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.utils.translation import gettext_lazy as _
from django.core.validators import EmailValidator
from django.contrib.auth.models import UserManager
from utils import UserTypeChoices


class AbstractUser(AbstractBaseUser, PermissionsMixin):
    """
    An abstract base class implementing a fully featured User model with
    admin-compliant permissions.

    Username and password are required. Other fields are optional.
    """

    username = models.CharField(
        _('username'),
        max_length=100,
        unique=True,
        help_text=_('Required. 150 characters or fewer. Letters, digits and -/_ only.'),
        error_messages={
            'unique': _("A user with that username already exists."),
        },
    )

    first_name = models.CharField(max_length=150,
                                  help_text="should be alpha only with max length 50")

    last_name = models.CharField(max_length=150,
                                  help_text="should be alpha only with max length 50")

    email = models.EmailField(_('email address'), validators=[EmailValidator], unique=True)

    phone = models.CharField(max_length=20, unique=True)

    type = models.SmallIntegerField(choices=UserTypeChoices.choices, default=UserTypeChoices.CUSTOMER)

    location = models.JSONField(blank=True, null=True)

    user_token = models.CharField(blank=True, null=True, max_length=500)

    last_order = models.DateTimeField(blank=True, null=True)

    requested_token = models.CharField(blank=True, null=True, max_length=500)

    registered = models.DateTimeField(auto_now_add=True)
    

    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )

    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )

    date_joined = models.DateTimeField(_('date joined'), auto_now_add=True)

    objects = UserManager()

    EMAIL_FIELD = 'email'

    USERNAME_FIELD = 'username'

    REQUIRED_FIELDS = ['email']

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')
        abstract = True
        db_table = 'users'

    def __str__(self) -> str:
        return str(self.email)

class User(AbstractUser):

    class Meta(AbstractUser.Meta):
        swappable = 'AUTH_USER_MODEL'

ecommerce/authenticate/views/login.py
from authenticate.serializers import LoginSerializer
from rest_framework.response import Response
from rest_framework.generics import CreateAPIView
from rest_framework_simplejwt.tokens import RefreshToken

class LoginView(CreateAPIView):
    serializer_class = LoginSerializer

    def post(self, request, *args, **kwargs):
        serializer = self.serializer_class(data=request.data)
        serializer.is_valid(raise_exception=True)
        user = serializer.validated_data['user']

        refresh = RefreshToken.for_user(user)
        return Response({
                'refresh': str(refresh),
                'access': str(refresh.access_token),
                'user_id': user.pk,
                'name' : f"{user.first_name} {user.last_name}"
        }, status=200)

ecommerce/reports/views/customers.py
from django.shortcuts import render, redirect
from users.models import User
from utils import UserTypeChoices, reports_admin_user
from datetime import date
from reports.generators import registered_users_per_month

@reports_admin_user
def customers_statistics(request):
    today = date.today()
    chart = registered_users_per_month()
    all_users = User.objects.filter(type=UserTypeChoices.CUSTOMER).count()
    active_users = User.objects.filter(type=UserTypeChoices.CUSTOMER, last_login__date=today).count()
    ordered_today = User.objects.filter(type=UserTypeChoices.CUSTOMER, last_order__date=today).count()
    new_users_month = User.objects.filter(type=UserTypeChoices.CUSTOMER, registered__month=today.month, registered__year=today.year).count()

    context = {
        'chart' : chart,
        'all_users' : all_users,
        'active_users' : active_users,
        'ordered_today' : ordered_today,
        'new_users_month' : new_users_month
    }
    return render(request, 'customers_stat.html', context)

ecommerce/reports/views/dashboard.py
from django.shortcuts import render, redirect
from orders.models import Order
from users.models import User
from utils import UserTypeChoices, reports_admin_user
from datetime import date, timedelta
from main.models import AppVersion
from reports.generators import orders_statistics_per_month_order
from main.models import Currency

@reports_admin_user
def dashboard(request):
    currency = Currency.objects.filter(default=True).last()
    orders_chart = orders_statistics_per_month_order()
    app_status = AppVersion.objects.last()
    if request.method == 'POST' and request.POST.get('app_status'):
        status = request.POST.get('app_status')
        app_status.active = True if status == 'active' else False
        app_status.save()
        return redirect('/')

    today = date.today()
    all_users = User.objects.filter(type=UserTypeChoices.CUSTOMER).count()
    today_orders = Order.objects.filter(created__date=today).count()
    yesterday_orders = Order.objects.filter(created__date=today - timedelta(1)).count()
    orders_per = (((today_orders - yesterday_orders) * 100) / yesterday_orders) if yesterday_orders != 0 else 100
    today_users = User.objects.filter(last_login__date=today, type=UserTypeChoices.CUSTOMER).count()
    today_sales = sum(i.total_cost for i in Order.objects.filter(created__date=today))
    context = {
        'all_users' : all_users,
        'today_orders' : today_orders,
        'today_users' : today_users,
        'today_sales' : today_sales,
        'today' : today,
        'yesterday_orders' : yesterday_orders,
        'orders_per' : orders_per,
        'app_status' : app_status.active,
        'orders_chart' : orders_chart,
        'currency' : currency,
    }
    return render(request, 'index.html', context)

ecommerce/reports/views/orders.py
from django.shortcuts import render, redirect
from orders.models import Order
from utils import  reports_admin_user, OrderStatusChoices
from datetime import date
from reports.generators import orders_statistics_per_month_order, statistics_filter_order
from django.db.models import Count
from django.core.paginator import Paginator
from django.http import HttpResponse
# from weasyprint import HTML
import tempfile
from django.template.loader import render_to_string
from main.models import Currency

@reports_admin_user
def orders_statistics(request):
    currency = Currency.objects.filter(default=True).last()
    today = date.today()
    year_chart = orders_statistics_per_month_order()
    month_chart = statistics_filter_order('Lmonth')
    week_chart = statistics_filter_order('Lweek')
    all_orders = Order.objects.all()
    pie_chart = (Order.objects.values('status').annotate(count=Count('status')).order_by())
    today_orders = Order.objects.filter(created__date=today).count()
    today_sales = sum(i.total_cost for i in Order.objects.filter(created__date=today, status=OrderStatusChoices.DELIVERED))
    overall_sales = sum(i.total_cost for i in Order.objects.filter(status=OrderStatusChoices.DELIVERED))
    context = {
        'year_chart' : year_chart,
        'month_chart' : month_chart,
        'week_chart' : week_chart,
        'all_orders' : all_orders.count(),
        'today_orders' : today_orders,
        'pie_chart' : pie_chart,
        'today_sales' : today_sales,
        'overall_sales' : overall_sales,
        'currency' : currency
    }
    return render(request, 'orders_stat.html', context)

@reports_admin_user
def all_orders(request):
    orders = Order.objects.all().select_related('customer', 'currency').order_by('-created')
    paginator = Paginator(orders, 10)
    page_number = request.GET.get('page')
    if page_number and not page_number.isdigit():
        return redirect('reports:unauthorized')
    page_obj = paginator.get_page(page_number)

    # Pagination Bar
    if page_number is not None and page_number not in ['1', '2'] and page_obj.paginator.num_pages > 5:
        previous = int(page_number) - 2
        next = int(page_number) + 3
        if int(page_number) == page_obj.paginator.num_pages:
            previous = int(page_number) - 4
        elif int(page_number)+1 >= page_obj.paginator.num_pages:
            previous = int(page_number) - 3
        if next > page_obj.paginator.num_pages:
            next = page_obj.paginator.num_pages + 1
        pagin_range = range(previous, next)
    else:
        previous = 1
        next = 6
        if next > page_obj.paginator.num_pages:
            next = page_obj.paginator.num_pages + 1
        pagin_range = range(previous, next)
    context = {
        'orders' : page_obj,
        'pagin_range' : pagin_range,
        'page_number' : int(page_number) if page_number else page_number,
    }
    return render(request, 'all_orders.html', context)

@reports_admin_user
def one_order(request, order_no):
    if request.method == 'POST' and request.POST.get('status'):
        order = Order.objects.filter(order_no=order_no).update(status=request.POST.get('status'))
    order = Order.objects.filter(order_no=order_no).select_related('customer', 'coupon', 'shipping_fees', 'address', 'address__country', 'address__city', 'currency').last()
    if not order:
        return redirect('reports:unauthorized')
    items = order.ordered_items.all().select_related('product', 'product__category').values('product__title', 'product__category__title', 'type', 'quantity', 'price')
    context = {
        'order' : order,
        'items' : items
    }
    return render(request, 'one_order.html', context)

@reports_admin_user
def order_pdf(request, id):
    order = Order.objects.select_related('customer', 'currency').filter(id=id).last()
    if not order:
        return redirect('reports:unauthorized')
    template = render_to_string("order-pdf.html", {'pagesize':'A3', 'order' : order, 'items' : order.ordered_items.all().select_related('product')})
    # html = HTML(string=template, base_url=request.build_absolute_uri())
    result = None #html.write_pdf()
    response = HttpResponse(content_type='application/pdf;')
    response['Content-Disposition'] = f'attachment; filename=order-{order.order_no}.pdf'
    response['Content-Transfer-Encoding'] = 'binary'
    with tempfile.NamedTemporaryFile(delete=True) as output:
        output.write(result)
        output.flush()
        output = open(output.name, 'rb')
        response.write(output.read())

    return response

ecommerce/reports/views/products.py
from django.shortcuts import render
from orders.models import Order, OrderItem
from utils import  reports_admin_user
from datetime import date
from reports.generators import registered_users_per_month
from products.models import Product

@reports_admin_user
def products_statistics(request):
    today = date.today()
    top_products_chart = Product.objects.all().order_by('-ordered_times')[:10]
    top_products_chart_data = {'product_name' : list(top_products_chart.values_list('title', flat=True)), 'ordered_times' : list(top_products_chart.values_list('ordered_times', flat=True))}
    all_products = Product.objects.all().count()
    active_products = Product.objects.filter(live=True).count()
    products_out_of_stock = Product.objects.filter(in_stock_items__lte=10).count()
    ordered_products_today = len(OrderItem.objects.filter(order__created__date=today).values('product__id').distinct())

    context = {
        'chart' : top_products_chart_data,
        'all_products' : all_products,
        'active_products' : active_products,
        'products_out_of_stock' : products_out_of_stock,
        'ordered_products_today' : ordered_products_today
    }
    return render(request, 'products_stat.html', context)


@reports_admin_user
def products_running_out(request):
    products = Product.objects.filter(in_stock_items__lte=100).order_by('-in_stock_items').select_related('category')
    context = {
        'products' : products
    }
    return render(request, 'products_running_out.html', context)

ecommerce/reports/templates/all_orders.html
{% extends 'base.html' %}
{% block title %}Wareix | All Orders{% endblock %}

{% block content %}

          <!-- Content wrapper -->
          <div class="content-wrapper">
            <!-- Content -->

            <div class="container-xxl flex-grow-1 container-p-y">
              <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Orders /</span> All Orders</h4>

              <!-- Basic Bootstrap Table -->

              <div class="card">
                <div class="table-responsive text-nowrap">
                  <table class="table">
                    <thead>
                      <tr>
                        <th>Order ID</th>
                        <th>Customer</th>
                        <th>Date</th>
                        <th>Total Cost</th>
                        <th>Status</th>
                        <th>Action</th>
                      </tr>
                    </thead>
                    <tbody class="table-border-bottom-0">
                      {% for order in orders %}
                      <tr class="table-normal">
                        <td><i class="fab fa-sketch fa-lg text-warning me-3"></i> <strong>{{order.id}}</strong></td>
                        <td>{{order.customer.first_name}} {{order.customer.last_name}}</td>
                        <td>{{order.created|date:'m-d-Y'}} </td>
                        <td>{{order.total_cost}} {{order.currency.symbol}}</td>
                        <td><span class="badge {% if order.status == 1 %}bg-label-primary{% elif order.status == 2 %}bg-label-warning{% elif order.status == 3 %}bg-label-success{% else %}bg-label-danger{% endif %} me-1">
                          {{order.get_status_display}}</span></td>
                        <td>
                          <div class="dropdown">
                            <button type="button" class="btn p-0 dropdown-toggle hide-arrow" data-bs-toggle="dropdown">
                              <i class="bx bx-dots-vertical-rounded"></i>
                            </button>
                            <div class="dropdown-menu">
                              <a class="dropdown-item" href="{% url 'reports:one-order' order.order_no %}"><i class="bx bx-edit-alt me-1"></i>View & Edit</a>
                              <a class="dropdown-item" href="{% url 'reports:order-pdf' order.id %}"><i class="bx bx-edit-alt me-1"></i>Download Invoice</a>
                            </div>
                          </div>
                        </td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                </div>
              </div>

              
              <!--/ Basic Bootstrap Table -->

              <!--/ Responsive Table -->
              <nav aria-label="Page navigation" style="padding-top: 1%;">
                <ul class="pagination justify-content-center">
                  <li class="page-item prev">
                    <a class="page-link" href="?page=1"><i class="tf-icon bx bx-chevrons-left"></i></a>
                  </li>
                  {% for p_r in pagin_range %}
                  <li class="page-item {% if page_number == p_r %}active{% endif %}">
                    <a class="page-link" href="?page={{p_r}}">{{p_r}}</a>
                  </li>
                  {% endfor %}
                  <li class="page-item next">
                    <a class="page-link" href="?page={{ orders.paginator.num_pages }}"><i class="tf-icon bx bx-chevrons-right"></i></a>
                  </li>
                </ul>
              </nav>
            </div>
            <!-- / Content -->

            
{% endblock %}

ecommerce/reports/templates/base.html
{% load static %}
<!DOCTYPE html>

<html
  lang="en"
  class="light-style layout-menu-fixed"
  dir="ltr"
>
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0"
    />

    <title>{% block title %} {% endblock %}</title>

    <meta name="description" content="" />

    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="{% static '/img/favicon/favicon.ico' %}" />


    <!-- Icons. Uncomment required icon fonts -->
    <link rel="stylesheet" href="{% static 'vendor/fonts/boxicons.css' %}" />

    <!-- Core CSS -->
    <link rel="stylesheet" href="{% static 'vendor/css/core.css' %}" class="template-customizer-core-css" />
    <link rel="stylesheet" href="{% static 'vendor/css/theme-default.css' %}" class="template-customizer-theme-css" />
    <link rel="stylesheet" href="{% static 'css/demo.css' %}" />

    <!-- Vendors CSS -->
    <!-- <link rel="stylesheet" href="{% static 'vendor/libs/perfect-scrollbar/perfect-scrollbar.css' %}" /> -->

    <link rel="stylesheet" href="{% static 'vendor/libs/apex-charts/apex-charts.css' %}" />

    <!-- Page CSS -->

    <!-- Helpers -->
    <script src="{% static 'vendor/js/helpers.js' %}"></script>

    <!--! Template customizer & Theme config files MUST be included after core stylesheets and helpers.js in the <head> section -->
    <!--? Config:  Mandatory theme config file contain global vars & default theme options, Set your preferred theme option in this file.  -->
    <script src="{% static 'js/config.js' %}"></script>
  </head>

  <body>
    <!-- Layout wrapper -->
    <div class="layout-wrapper layout-content-navbar">
      <div class="layout-container">
        <!-- Menu -->

        <aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme">
          <div class="app-brand demo">
            <a href="/" class="app-brand-link">
              
              <span class="app-brand-text demo menu-text fw-bolder ms-2">Wareix</span>
            </a>

            <a href="javascript:void(0);" class="layout-menu-toggle menu-link text-large ms-auto d-block d-xl-none">
              <i class="bx bx-chevron-left bx-sm align-middle"></i>
            </a>
          </div>

          <div class="menu-inner-shadow"></div>

          <ul class="menu-inner py-1">
            <!-- Dashboard -->
            <li class="menu-item active">
              <a href="/" class="menu-link">
                <i class="menu-icon tf-icons bx bx-home-circle"></i>
                <div data-i18n="Analytics">Dashboard</div>
              </a>
            </li>

            <li class="menu-header small text-uppercase">
              <span class="menu-header-text">Customers</span>
            </li>
            <li class="menu-item">
              <a href="{% url 'reports:customer-statistics' %}" class="menu-link">
                <i class="menu-icon tf-icons bx bx-user"></i>
                <div data-i18n="Tables">Customer Statistics</div>
              </a>
            </li>
            <li class="menu-item">
              <a href="tables-basic.html" class="menu-link">
                <i class="menu-icon tf-icons bx bx-notification"></i>
                <div data-i18n="Tables">Send Notification</div>
              </a>
            </li>

            <li class="menu-header small text-uppercase">
              <span class="menu-header-text">Products</span>
            </li>
            <li class="menu-item">
              <a href="{% url 'reports:product-statistics' %}" class="menu-link">
                <i class="menu-icon tf-icons bx bx-cube"></i>
                <div data-i18n="Tables">Product Statistics</div>
              </a>
            </li>
            <li class="menu-item">
              <a href="{% url 'reports:products-running-out' %}" class="menu-link">
                <i class="menu-icon tf-icons bx bx-time"></i>
                <div data-i18n="Tables">Products running out</div>
              </a>
            </li>

            <li class="menu-header small text-uppercase">
              <span class="menu-header-text">Orders</span>
            </li>
            <li class="menu-item">
              <a href="{% url 'reports:order-statistics' %}" class="menu-link">
                <i class="menu-icon tf-icons bx bx-search"></i>
                <div data-i18n="Tables">Order Statistics</div>
              </a>
            </li>
            <li class="menu-item">
              <a href="{% url 'reports:all-orders' %}" class="menu-link">
                <i class="menu-icon tf-icons bx bx-folder-open"></i>
                <div data-i18n="Tables">All Orders</div>
              </a>
            </li>
            <li class="menu-header small text-uppercase">
              <span class="menu-header-text">Reports</span>
            </li>
            <li class="menu-item">
              <a href="{% url 'reports:sheets' %}" class="menu-link">
                <i class="menu-icon tf-icons bx bx-spreadsheet"></i>
                <div data-i18n="Tables">Excel Sheets</div>
              </a>
            </li>
        </aside>
        <!-- / Menu -->

        <!-- Layout container -->
        <div class="layout-page">
          <!-- Navbar -->

          <nav
            class="layout-navbar container-xxl navbar navbar-expand-xl navbar-detached align-items-center bg-navbar-theme"
            id="layout-navbar"
          >
            <div class="layout-menu-toggle navbar-nav align-items-xl-center me-3 me-xl-0 d-xl-none">
              <a class="nav-item nav-link px-0 me-xl-4" href="javascript:void(0)">
                <i class="bx bx-menu bx-sm"></i>
              </a>
            </div>

            <div class="navbar-nav-right d-flex align-items-center" id="navbar-collapse">
              
              <ul class="navbar-nav flex-row align-items-center ms-auto">
                <!-- Place this tag where you want the button to render. -->
                
                <!-- User -->
                <li class="nav-item navbar-dropdown dropdown-user dropdown">
                  <a class="nav-link dropdown-toggle hide-arrow" href="javascript:void(0);" data-bs-toggle="dropdown">
                    <div class="avatar avatar-online">
                      <img src="{% static 'img/avatars/1.png' %}" alt class="w-px-40 h-auto rounded-circle" />
                    </div>
                  </a>
                  <ul class="dropdown-menu dropdown-menu-end">
                    <li>
                      <a class="dropdown-item" href="#">
                        <div class="d-flex">
                          <div class="flex-shrink-0 me-3">
                            <div class="avatar avatar-online">
                              <img src="{% static 'img/avatars/1.png' %}" alt class="w-px-40 h-auto rounded-circle" />
                            </div>
                          </div>
                          <div class="flex-grow-1">
                            <span class="fw-semibold d-block">{{request.user.first_name}}</span>
                            <small class="text-muted">{{request.user.get_type_display}}</small>
                          </div>
                        </div>
                      </a>
                    </li>
                    <li>
                    </li>
                      <div class="dropdown-divider"></div>
                    </li>
                    <li>
                      <a class="dropdown-item" href="{% url 'reports:logout' %}">
                        <i class="bx bx-power-off me-2"></i>
                        <span class="align-middle">Log Out</span>
                      </a>
                    </li>
                  </ul>
                </li>
                <!--/ User -->
              </ul>
            </div>
          </nav>

          <!-- / Navbar -->

          <!-- Content wrapper -->
          <div class="content-wrapper">
            <!-- Content -->

            {% block content %}

            {% endblock %}
            <!-- / Content -->

            <!-- Footer -->
            <footer class="content-footer footer bg-footer-theme">
              <div class="container-xxl d-flex flex-wrap justify-content-between py-2 flex-md-row flex-column">
                <div class="mb-2 mb-md-0">
                  ©
                  <script>
                    document.write(new Date().getFullYear());
                  </script>
                  , made with ❤️ by
                  <a href="https://www.ware-ix.com" target="_blank" class="footer-link fw-bolder">Wareix</a>
                </div>
                
              </div>
            </footer>
            <!-- / Footer -->

            <div class="content-backdrop fade"></div>
          </div>
          <!-- Content wrapper -->
        </div>
        <!-- / Layout page -->
      </div>

      <!-- Overlay -->
      <div class="layout-overlay layout-menu-toggle"></div>
    </div>
    <!-- / Layout wrapper -->

    <!-- Core JS -->
    <!-- build:js assets/vendor/js/core.js -->
    <!-- <script src="{% static 'vendor/libs/jquery/jquery.js' %}"></script> -->
    <!-- <script src="{% static 'vendor/libs/popper/popper.js' %}"></script> -->
    <script src="{% static 'vendor/js/bootstrap.js' %}"></script>
    <!-- <script src="{% static 'vendor/libs/perfect-scrollbar/perfect-scrollbar.js' %}"></script> -->

    <script src="{% static 'vendor/js/menu.js' %}"></script>
    <!-- endbuild -->

    <!-- Vendors JS -->
    <script src="{% static 'vendor/libs/apex-charts/apexcharts.js' %}"></script>

    <!-- Main JS -->
    <script src="{% static 'js/main.js' %}"></script>

    {% block scripts %} {% endblock %}
  </body>
</html>